name: app_segundo_parcial
description: Una app Flutter para guardar lugares favoritos con imagen y ubicación.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3
  sqflite: ^2.3.0
  location: ^5.0.3
  google_maps_flutter: ^2.5.0
  http: ^0.13.6
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/places.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "dev_assets/places-adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
